name: myguide
description: Art makes better place.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase stack
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_storage: ^11.0.10
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1

  # State management
  flutter_riverpod: ^2.1.3

  # Routing
  go_router: ^6.0.1
  equatable: ^2.0.5
  cloud_functions: ^4.0.7

  intl: ^0.18.0
  image_picker: ^0.8.6

  url_launcher: ^6.1.7
  uuid: ^3.0.7
  loading_animation_widget: ^1.2.0+4
  beamer: ^1.5.3
  barcode: ^2.2.3
  file_saver: ^0.1.1
  cached_network_image: ^3.2.3
  awesome_dialog: ^3.0.2

  collection: ^1.17.0

dependency_overrides:
  intl: ^0.18.0
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/
    - assets/artworks/

